[package]
name = "ssccpp"
version = "0.1.0"
authors = ["CARCANO Arthur <arthur.carcano@inria.fr>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = '2'
hostname = '*'
regex = "1"
walkdir = "2"
